name: 'ContinuousSquares'
version: 0
            
training: 
  stochastic: False
  prop_gold: 0.
  denoising: False
  adversial: False
  share_enc: False
  share_dec: False
  noise_function: 'gaussian'
  noise_intensity: 0.05
  adversial_patience: 1
  batch_size: 64
  lr: 0.01
  lr adversial: 0.001
  n_epochs: 10
  analyse_every: 50

dataset:
  size: 50000
  L:
    positions:
      x_min: -3
      x_max: 3
      y_min: -1
      y_max: 1
    dim: 2
  L1:
    positions:
      x_min: -3
      x_max: -1
      y_min: -1
      y_max: 1
    probs:
      top_left: 0.25
      bottom_left: 0.25
      top_right: 0.25
      bottom_right: 0.25
  L2:
    positions:
      x_min: 1
      x_max: 3
      y_min: -1
      y_max: 1
    probs:
      top_left: 0.25
      bottom_left: 0.25
      top_right: 0.25
      bottom_right: 0.25
  M:
    dim: 2
    a11: 1.
    a21: 0.5
    a12: -1.
    a22: -0.3


models:
  encoder:
    model: "linear"
    batch_norm: True
    linear:
      dim_in: 2
      dim_out: 2
      bias: True
    mlp:
      dim_in: 2
      dim_hidden: 16
      dim_out: 2
  decoder:
    model: "linear"
    linear:
      dim_in: 2
      dim_out: 2
      bias: True
    mlp:
      dim_in: 2
      dim_hidden: 3
      dim_out: 2
  discriminator:
    model: "mlp"
    linear:
      dim_in: 2
      dim_out: 1
    mlp:
      dim_in: 2
      dim_hidden: 3
      dim_out: 1

  
            
            

      